image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive
  - ps: |
      Write-Host "Installing Azure storage emulator..." -ForegroundColor Cyan
      Write-Host "Downloading..."
      $msiPath = "$($env:USERPROFILE)\MicrosoftAzureStorageEmulator.msi"
      (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/F/3/8/F3857A38-D344-43B4-8E5B-2D03489909B9/MicrosoftAzureStorageEmulator.msi', $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /i "$msiPath" /q
      del $msiPath
      Write-Host "Installed Azure storage emulator" -ForegroundColor Green
build: off

build_script:
  - cmd: msbuild /t:restore
  - cmd: msbuild /p:VersionSuffix="alpha%APPVEYOR_BUILD_NUMBER%" /p:Configuration=Release

artifacts:
  - path: '**\bin\*\*.nupkg'

skip_branch_with_pr: true

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package