language: csharp
matrix:
  include:
    - os: linux
    - os: osx

solution: Keyczure.sln

mono:
  - beta

install:
  - msbuild /t:restore

script:
 - msbuild
 - .ci/RunTests.sh

branches:
  only:
    - master